var graph = {
  "nodes":[
    {"id":"User","group":0, type:"human", "children":[]},
    {"id":"Maintainer","group":0, type:"human", "children":[]},
    {"id":"Linked_Open_Metadata_Store","group":1, type:"http", "children":["https://dydra.com/luca-gramaglia/eu-us-partnership-metadata-store/sparql"]},
    {"id":"Local_Metadata_Cache","group":1, type:"cache", "children":[".libPaths()/project-eu-us/data/"]},
    {"id":"CodeList_To_RDF","group":2, type:"interfx", "children":[]},
    {"id":"Dataflow_To_RDF","group":2, type:"interfx", "children":[]},
    {"id":"DSD_to_RDF","group":2, type:"interfx", "children":[]},
    {"id":"Harmonised_Dataset_To_RDF","group":3, type:"beProc", "children":[]},
    {"id":"Geo_GeoCode","group":3, type:"beProc", "children":[]},
    {"id":"Mappings_To_RDF","group":3, type:"beProc",  "children":[]},
    {"id":"Create_RDF_Component_Map","group":4, type:"interfx", "children":[]},
    {"id":"Create_RDF_Structure_Map","group":4, type:"interfx", "children":[]},
    {"id":"Create_RDF_Value_Map","group":4, type:"interfx", "children":[]},
    {"id":"Create_RDF_Dataset","group":5, type:"interfx", "children":[]},
    {"id":"Create_RDF_DSD","group":5, type:"interfx", "children":[]},
    {"id":"large.query.handler","group":6, type:"interfx", "children":[]},
    {"id":"query.builder","group":6, type:"interfx", "children":[]},
    {"id":"Blank_ID","group":6, type:"interfx", "children":[]},
    {"id":"SDMX_To_RDF","group":7, type:"beProc", "children":["SPARQL.endpoint", "dataset.name"]},
    {"id":"BEA_To_RDF","group":7, type:"beProc", "children":[]},
    {"id":"Get_Dataset","group":8, type:"feProc", "children":[]},
    {"id":"List_Available_Datsets","group":8, type:"feProc", "children":[]},
    {"id":"Search_Dataset","group":8, type:"feProc", "children":[]},
    {"id":"Describe_Dataset","group":8, type:"feProc", "children":[]},
    {"id":"Dataset_Template","group":9, type:"csv", "children":[]},
    {"id":"DSD_Template","group":9, type:"csv", "children":[]},
    {"id":"Structure_Map_Template","group":10, type:"csv", "children":[]},
    {"id":"Component_Map_Template","group":10, type:"csv", "children":[]},
    {"id":"Value_Map_Template","group":10, type:"csv", "children":[]},
    {"id":"BEA_API","group":11, type:"http", "children":[]},
    {"id":"eurostat_API","group":11, type:"http", "children":[]},
    {"id":"beaSearch","group":12, type:"beaR", "children":[]},
    {"id":"beaGet","group":12, type:"beaR", "children":[]},
    {"id":"readSDMX","group":12, type:"rsdmx", "children":[]},
    {"id":"SPARQL","group":12, type:"SPARQL", "children":[]}
  ],
  "links":[
    {"source":"Maintainer","target":"SDMX_To_RDF","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"query.builder","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"large.query.handler","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"Blank_ID","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"Dataflow_To_RDF","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"DSD_To_RDF","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"CodeList_To_RDF","value":1, "passes":"", "receives":""},
    {"source":"SDMX_To_RDF","target":"readSDMX","value":1, "passes":"", "receives":""},
    {"source":"BEA_To_RDF","target":"beaGet","value":1, "passes":"", "receives":""}
  ]
}